### PR TITLE
Migrate to HomeAssistant 2025.6

### PR DESCRIPTION
**Pull request by jankaderabek**
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

```
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

Tested on my instance/fork https://github.com/jankaderabek/custom_vesync

### CODE REVIEW

**Comment by corgan2222** [comment]
works great! Thanks a lot!

**Comment by joneselliot** [comment]
Noob here - how can I test this before it's merged?

**Comment by jsheputis** [comment]
> Noob here - how can I test this before it's merged?

@joneselliot This might work, calling the `update.install` action on the latest commit in this PR

```yaml
action: update.install
data:
  version: 09d8bfda2bf2cf4f5b2bf5bb7c5cb6aa3108f6e6
target:
  entity_id: update.custom_vesync_update
```

**Comment by jsheputis** [comment]
+1 On this resolving issues in `2025.6` for myself as well.

**Comment by jankaderabek** [comment]
Btw I just found this repo which is listed in HACS and it works fine, showing all entities for my device and it works on 2025.6, also seems to be actively maintained https://github.com/haext/custom_vesync

**Comment by joneselliot** [comment]
Awesome, this one works great. Thank you!

Elliot Jones (he/him/his) | Application Developer II
________________________________

**Comment by amferguson** [comment]
> > Noob here - how can I test this before it's merged?
> 
> @joneselliot This might work, calling the `update.install` action on the latest commit in this PR
> 
> ```yaml
> action: update.install
> data:
>   version: 09d8bfda2bf2cf4f5b2bf5bb7c5cb6aa3108f6e6
> target:
>   entity_id: update.custom_vesync_update
> ```

Thank you, this worked perfectly for me! Does anyone know when this might be merged in?

**Comment by sillvva** [comment]
Any chance this ever gets merged?

**Comment by Fluffy-Bunny-23** [comment]
Is there a working fork right now that I can use while this gets merged?

**Comment by sillvva** [comment]
@micahqcade

**Comment by fcastilloec** [comment]
> Is there a working fork right now that I can use while this gets merged?

I'm currently using https://github.com/haext/custom_vesync
It feels a little more active, and it's been working great so far.
